### ISSUE TITLE
recompilation

### ISSUE THREAD

**Issue by tahaeghtesad** [Semantic-Org/Semantic-UI-ar#4]
Could you plz recompile semantic-ui-ar for semantic-ui 1.7.3?

**Comment by MohammadYounes** [comment]
As of 1.7.0 the main repo has RTL support built-in, its still not documented nor reflected on the docs site. 

> **semantic-ui-ar repo is deprecated.**

To get the RTL version of the main repo, do:

1. Clone the repo.
2. Update `tasks/defaults.js` and set `rtl: true`.
3. Follow the steps mentioned [here](https://github.com/Semantic-Org/Semantic-UI#recommended-usage-themed).

  The following commands are also available (still not documented)
  ```
  gulp "build rtl" // build all files from source
  gulp "watch rtl" // watch files
  ```

If you need further assistance! just let me know. 

Thanks.
