### ISSUE TITLE
Getting Started Guide and Examples

### ISSUE THREAD

**Issue by mixerp** [Semantic-Org/Semantic-UI-ar#5]
To start off, thank you for the great css component framework. We shifted our open source software from bootstrap to semantic ui about a year ago. Demo here:

http://chamlang.mixerp.org/

Could you please share the documentation or first step guide to setup RTL support in Semantic UI?  The official semantic ui page looks a little incomplete to me:

![rtl-semantic](https://cloud.githubusercontent.com/assets/5273383/9027517/ff5dfae2-3977-11e5-9634-406f2b2fe81f.png)

Help.

**Comment by MohammadYounes** [comment]
Hi,

Up to now the docs site is still not using the RTL version of the library. What you see is still the LTR version with a direction change only.

As of 1.7.0 the [main repo](https://github.com/Semantic-Org/Semantic-UI) has RTL support built-in, You need to make a local build with [RTL flag](https://github.com/Semantic-Org/Semantic-UI/blob/master/tasks/config/defaults.js#L17) enabled and the RTL files will be generated for you.

If you need further assistance, please let me know!

Thanks.

**Comment by MohammadYounes** [comment]
@mixerp Also you can follow the steps described [here](http://semantic-ui.com/introduction/getting-started.html) (Video included) and select to build the RTL version.

**Comment by mixerp** [comment]
Many thanks Mohammad. I will keep in touch with you.

**Comment by mixerp** [comment]
Thank you guys. Semantic UI looks excellent on RTL as well. Keep up the good work!!!!!
